name: Set up Linux dependencies
description: Install native build and execution dependencies

runs:
  using: composite
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          bubblewrap \
          libappindicator3-dev \
          librsvg2-dev \
          libwebkit2gtk-4.1-dev \
          patchelf \
          xdg-utils
