[package]
name = "huddol-app"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true

[package.metadata.release]
pre-release-hook = ["node", "../scripts/release-hook.mjs"]

[lib]
crate-type = ["rlib"]
name = "huddol_app_lib"

[dependencies]
anyhow = "1"
serde_json = "1"
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
tauri-plugin-single-instance = "2"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[target."cfg(windows)".dependencies]
windows-sys = { version = "0.61", features = ["Win32_UI_WindowsAndMessaging"] }

[features]
