[package]
name = "huddol-app"
version.workspace = true
description.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
name = "huddol_app_lib"
crate-type = ["rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
anyhow = "1"
serde_json = "1"
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
tauri-plugin-single-instance = { path = "vendor/tauri-plugin-single-instance-2.4.3/crate", version = "=2.4.3" }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_UI_WindowsAndMessaging"] }

[features]
